<template>
<div id="app">
  <transition name="qinban-loading">
    <div v-if="isBooting" class="qinban-loading" role="status" aria-label="亲伴正在打开">
      <div class="loading-brand"><div class="brand-mark"><img src="/assets/qinban-icon.svg" alt="" /></div><strong>亲伴</strong></div>
      <div class="loading-scene" aria-hidden="true">
        <svg viewBox="0 0 520 300" role="presentation">
          <path class="scene-horizon" d="M44 237C133 213 188 223 260 238s127 26 216-4"/>
          <path class="scene-link" d="M137 211C189 155 221 157 260 191s70 36 123-21"/>
          <circle class="scene-link-dot" cx="260" cy="190" r="7"/>
          <circle class="scene-link-dot small" cx="217" cy="170" r="4"/>
          <circle class="scene-link-dot small" cx="304" cy="180" r="4"/>
          <g class="scene-person scene-person-human">
            <circle cx="126" cy="131" r="19"/>
            <path d="M91 216c3-38 16-58 35-58s32 20 35 58Z"/>
            <path class="scene-face" d="M139 130l8 4-8 3"/>
          </g>
          <g class="scene-person scene-person-memory">
            <circle cx="394" cy="122" r="18"/>
            <path d="M361 216c3-39 15-61 33-61s30 22 33 61Z"/>
            <path class="scene-face" d="M381 121l-8 4 8 3"/>
            <path class="scene-glow" d="M394 84V69M362 96l-10-10M426 96l10-10"/>
          </g>
          <path class="scene-ground" d="M54 239c62-13 104-13 154-2M312 237c54-10 101-10 154 1"/>
        </svg>
      </div>
      <p class="loading-caption">正在连接记忆</p>
      <div class="loading-dots" aria-hidden="true"><i></i><i></i><i></i></div>
    </div>
  </transition>
  <div class="app-shell" :class="['theme-'+settings.theme,'font-'+settings.fontSize]" :style="{'--bubble-radius':settings.bubbleRadius+'px','--message-gap':settings.messageGap+'px'}">
    <aside class="sidebar">
      <div class="brand-lockup"><div class="brand-mark"><img src="/assets/qinban-icon.svg" alt="" /></div><div><div class="brand-name">亲伴</div><div class="brand-caption">让珍贵的记忆，继续陪伴</div></div></div>
      <nav class="primary-nav"><button v-for="item in navItems" :key="item.id" class="nav-link" :class="{active:activeView===item.id}" @click="navigate(item.id)"><span class="nav-icon" v-html="icon(item.icon)"></span><span>{{item.label}}</span></button></nav>
      <div class="sidebar-footer"><div class="local-badge">前端原型 · 本机数据</div><button class="sidebar-help" @click="showAbout=true"><span v-html="icon('info')"></span>产品说明</button></div>
    </aside>

    <main class="workspace">
      <header v-if="activeView!=='inbox'" class="topbar" :class="{'is-chat':activeView==='chat'}">
        <button v-if="isSecondaryView" class="back-button" @click="goBackSecondary"><span v-html="icon('arrow-left')"></span></button>
        <div class="mobile-brand" v-if="activeView!=='chat'&&!isSecondaryView"><div class="brand-mark small"><img src="/assets/qinban-icon.svg" alt="" /></div><strong>亲伴</strong></div>
        <div class="topbar-heading" v-if="activeView!=='chat'"><h1>{{viewTitle}}</h1><p>{{viewSubtitle}}</p></div>
        <div class="topbar-actions">
          <button v-if="activeView==='contacts'||activeView==='studio'" class="primary-action compact" @click="openNewCompanion"><span v-html="icon('plus')"></span>新建 AI</button>
          <button v-if="activeView==='moments'" class="primary-action compact" @click="openMomentDialog"><span v-html="icon('plus')"></span>发布动态</button>
          <button v-if="activeView==='memory-lab'" class="primary-action compact" @click="openMemoryDialog()"><span v-html="icon('plus')"></span>添加记忆</button>
          <button v-if="activeView==='ai-detail'" class="primary-action compact" @click="saveCompanionDetails"><span v-html="icon('check')"></span>保存角色</button>
        </div>
      </header>

      <section class="content-area" :class="{'chat-content':activeView==='chat','inbox-content':activeView==='inbox'}">
        <!-- 会话：首页固定在应用视口内，聊天记录在右侧内部滚动 -->
        <div v-if="activeView==='inbox'" class="inbox-layout page-enter">
          <section class="conversation-panel card-surface">
            <label class="search-box"><span v-html="icon('search')"></span><input ref="searchInput" v-model="searchQuery" placeholder="搜索好友、群聊或消息" /></label>
            <div class="conversation-list">
              <button v-for="thread in filteredThreads" :key="thread.type+thread.threadId" class="conversation-item" :class="{active:activeChatRef&&activeChatRef.type===thread.type&&activeChatRef.id===thread.threadId}" @click="openThread(thread.type,thread.threadId)">
                <div class="avatar" :style="avatarStyle(thread)"><span v-if="!thread.avatarImage">{{thread.initial||thread.name.slice(0,1)}}</span><i v-if="thread.type==='companion'&&thread.online" class="online-dot"></i><b v-if="thread.type==='group'" class="group-mark">群</b></div>
                <div class="conversation-copy"><div><strong>{{thread.name}}</strong><time>{{lastMessageTime(thread)}}</time></div><p>{{thread.lastMessage}}</p></div><span v-if="thread.unread" class="unread-dot"></span>
              </button>
              <div v-if="!filteredThreads.length" class="mini-empty">没有匹配的会话</div>
            </div>
            <button class="new-conversation" @click="openNewCompanion"><span v-html="icon('plus')"></span>创建一位 AI 好友</button>
          </section>
          <section class="chat-panel"><chat-view v-if="activeThread" :thread="activeThread" :companions="companions" :messages="activeMessages" :is-replying="isReplying" :input-message="inputMessage" :api-active="activeChatApiReady" @update-input="inputMessage=$event" @send="sendMessage" @quick="sendQuickMessage" @proactive="sendProactiveMessage(activeThread)" @back="closeChat" @open-settings="openChatSettings(activeThread)" @notice="showToast"></chat-view></section>
        </div>
        <div v-if="activeView==='chat'&&activeThread" class="chat-route page-enter"><chat-view :thread="activeThread" :companions="companions" :messages="activeMessages" :is-replying="isReplying" :input-message="inputMessage" :api-active="activeChatApiReady" @update-input="inputMessage=$event" @send="sendMessage" @quick="sendQuickMessage" @proactive="sendProactiveMessage(activeThread)" @back="closeChat" @open-settings="openChatSettings(activeThread)" @notice="showToast"></chat-view></div>

        <!-- AI 通讯录 -->
        <div v-if="activeView==='contacts'" class="contacts-page page-enter page-width">
          <div class="list-toolbar"><label class="search-box"><span v-html="icon('search')"></span><input v-model="searchQuery" placeholder="搜索 AI 好友" /></label><div class="filter-pills"><button v-for="filter in contactCategories" :key="filter" :class="{active:contactFilter===filter}" @click="contactFilter=filter">{{filter==='all'?'全部':filter==='online'?'在线':filter}}</button></div></div>
          <div class="contact-grid"><article v-for="item in filteredContacts" :key="item.id" class="contact-card card-surface"><div class="contact-head"><div class="avatar large" :style="avatarStyle(item)"><span v-if="!item.avatarImage">{{item.initial}}</span><i v-if="item.online" class="online-dot"></i></div><div><span class="category-tag">{{item.category}}</span><h3>{{item.name}}</h3><p>{{item.tagline}}</p></div></div><div class="tag-row"><span v-for="tag in capabilityNames(item)" :key="tag">{{tag}}</span><span v-if="!capabilityNames(item).length">纯文本</span></div><div class="contact-meta"><span><b>{{(item.memories||[]).length}}</b> 条记忆</span><span><b>{{item.proactive?.enabled?'开启':'暂停'}}</b> 主动消息</span></div><div class="card-actions"><button class="primary-action" @click="openThread('companion',item.id)"><span v-html="icon('message')"></span>聊天</button><button class="secondary-action" @click="openCompanionEditor(item)">编辑角色</button><button class="icon-action" @click="openGroupDialog(null,item.id)"><span v-html="icon('group')"></span></button></div></article></div>
        </div>

        <!-- AI 朋友圈 -->
        <div v-if="activeView==='moments'" class="moments-page page-enter page-width narrow-page">
          <div class="moment-feed"><article v-for="moment in moments" :key="moment.id" class="moment-card card-surface"><div class="moment-author"><div class="avatar" :style="avatarStyle(momentAuthor(moment))"><span v-if="!momentAuthor(moment).avatarImage">{{momentAuthor(moment).initial}}</span></div><div><strong>{{momentAuthor(moment).name}}</strong><span>{{formatRelativeTime(moment.createdAt)}} · {{moment.visibility}}</span></div><button class="icon-action" @click="toggleMomentSave(moment)" :class="{active:moment.saved}"><span v-html="icon('bookmark')"></span></button></div><p class="moment-text">{{moment.content}}</p><div v-if="moment.imageTone" class="moment-image" :class="moment.imageTone"><span v-html="icon('image')"></span><small>图片内容占位 · 等待后端生成或上传</small></div><div class="moment-actions"><button :class="{liked:moment.liked}" @click="toggleMomentLike(moment)"><span v-html="icon('heart')"></span>{{moment.liked?'已赞':'点赞'}}</button><button><span v-html="icon('comment')"></span>{{moment.comments.length}} 评论</button><span>{{moment.likes.length?moment.likes.join('、')+' 觉得很暖':'还没有点赞'}}</span></div><div v-if="moment.comments.length" class="comment-list"><p v-for="c in moment.comments" :key="c.id"><strong>{{c.author}}</strong> {{c.content}}</p></div><div class="comment-composer"><input v-model="commentDrafts[moment.id]" @keydown.enter="addMomentComment(moment)" placeholder="写一句回应…"/><button @click="addMomentComment(moment)">发送</button></div></article></div>
        </div>
        <!-- AI 与群聊工作台 -->
        <div v-if="activeView==='studio'" class="studio-page page-enter page-width">
          <div class="metric-grid"><article><span v-html="icon('sparkle')"></span><div><strong>{{companions.length}}</strong><small>AI 角色</small></div></article><article><span v-html="icon('group')"></span><div><strong>{{groups.length}}</strong><small>AI 群聊</small></div></article><article><span v-html="icon('send')"></span><div><strong>{{proactiveCount}}</strong><small>允许主动消息</small></div></article><article><span v-html="icon('settings')"></span><div><strong>0</strong><small>真实后端任务</small></div></article></div>
          <div class="studio-grid">
            <section class="studio-section card-surface"><div class="panel-title"><div><span class="soft-label">AI CHARACTERS</span><h2>AI 好友角色</h2></div><button class="secondary-action" @click="openNewCompanion"><span v-html="icon('plus')"></span>新建</button></div><div class="asset-list"><article v-for="item in companions" :key="item.id" class="asset-row"><div class="avatar" :style="avatarStyle(item)"><span v-if="!item.avatarImage">{{item.initial}}</span></div><div><strong>{{item.name}}</strong><p>{{item.persona.relationship}} · {{item.category}}</p><div class="mini-tags"><span v-for="tag in capabilityNames(item).slice(0,3)" :key="tag">{{tag}}</span></div></div><button @click="openCompanionEditor(item)"><span v-html="icon('edit')"></span></button></article></div></section>
            <section class="studio-section card-surface"><div class="panel-title"><div><span class="soft-label">MULTI AI CHAT</span><h2>AI 群聊</h2></div><button class="secondary-action" @click="openGroupDialog()"><span v-html="icon('plus')"></span>创建群聊</button></div><div class="asset-list"><article v-for="group in groups" :key="group.id" class="asset-row group-row"><div class="avatar" :style="avatarStyle(group)"><span v-if="!group.avatarImage">{{group.initial}}</span><b class="group-mark">群</b></div><div><strong>{{group.name}}</strong><p>{{memberNames(group)}}</p><div class="mini-tags"><span>{{group.strategy.enabled?'主动群聊开启':'主动群聊暂停'}}</span><span>{{group.strategy.mode==='random'?'随机发言':'顺序发言'}}</span></div></div><button @click="openGroupDialog(group)"><span v-html="icon('settings')"></span></button><button @click="openThread('group',group.id)"><span v-html="icon('message')"></span></button></article></div></section>
          </div>
          <section class="backend-handoff card-surface"><div class="panel-title"><div><span class="soft-label">BACKEND HANDOFF</span><h2>后端接入清单</h2><p>页面结构已预留，当前均未连接真实服务。</p></div><span class="status-chip pending">前端待审核</span></div><div class="handoff-grid"><div><span v-html="icon('database')"></span><strong>会话与长期记忆</strong><p>消息存储、摘要、关系事件、向量索引</p><em>待后端接入</em></div><div><span v-html="icon('group')"></span><strong>多 AI 调度</strong><p>发言顺序、冷却、上下文隔离、并发控制</p><em>待后端接入</em></div><div><span v-html="icon('bell')"></span><strong>主动消息任务</strong><p>时间窗、频率、每日上限与离线队列</p><em>待后端接入</em></div><div><span v-html="icon('shield')"></span><strong>安全与权限</strong><p>密钥代理、内容过滤、声音授权与审计</p><em>待后端接入</em></div></div></section>
        </div>

        <!-- 单个 AI 详细设置 -->
        <div v-if="activeView==='ai-detail'&&companionForm.persona" class="ai-detail-page page-enter page-width">
          <aside class="ai-profile-aside card-surface"><div class="avatar hero-avatar" :style="avatarStyle(companionForm)"><span v-if="!companionForm.avatarImage">{{companionForm.initial||companionForm.name?.slice(0,1)||'AI'}}</span></div><h2>{{companionForm.name||'新的 AI 好友'}}</h2><p>{{companionForm.tagline||'为这段关系写一句简单介绍'}}</p><label class="avatar-upload"><input type="file" accept="image/*" @change="handleImageUpload($event,'companion')"/><span v-html="icon('image')"></span>更换头像</label><div class="aside-meta"><span><b>{{(companionForm.memories||[]).length}}</b> 条记忆</span><span><b>{{capabilityNames(companionForm).length}}</b> 项能力</span></div><div class="backend-note"><span v-html="icon('info')"></span><p>这里只保存前端配置。角色提示词、记忆检索与模型能力需要后端按字段接入。</p></div></aside>
          <section class="ai-config card-surface"><div class="tab-strip scroll-tabs"><button v-for="tab in [{id:'profile',name:'基础资料'},{id:'persona',name:'人设'},{id:'memory',name:'记忆'},{id:'style',name:'对话风格'},{id:'proactive',name:'主动陪伴'},{id:'ability',name:'能力'}]" :key="tab.id" :class="{active:aiDetailTab===tab.id}" @click="aiDetailTab=tab.id">{{tab.name}}</button></div>
            <div class="config-scroll">
              <div v-if="aiDetailTab==='profile'" class="form-section"><div class="section-heading"><h3>基础资料</h3><p>关系入口和通讯录中展示的信息。</p></div><div class="form-grid"><label class="form-field"><span>名称</span><input v-model="companionForm.name" placeholder="例如：沐沐"/></label><label class="form-field"><span>文字头像</span><input v-model="companionForm.initial" maxlength="2" placeholder="沐"/></label><label class="form-field"><span>角色分类</span><select v-model="companionForm.category"><option>温柔陪伴</option><option>知心朋友</option><option>灵感导师</option><option>生活搭档</option><option>自定义</option></select></label><label class="form-field"><span>主题颜色</span><input v-model="companionForm.color" type="color"/></label><label class="form-field full"><span>一句话介绍</span><input v-model="companionForm.tagline" placeholder="TA 会如何陪伴你"/></label><label class="form-field"><span>绑定 API 配置</span><select v-model="companionForm.apiProfileId"><option v-for="p in apiProfiles" :key="p.id" :value="p.id">{{p.name}}</option></select></label><div class="toggle-field"><div><strong>通讯录在线状态</strong><span>仅前端展示状态</span></div><button class="switch" :class="{on:companionForm.online}" @click="companionForm.online=!companionForm.online"><i></i></button></div></div></div>
              <div v-if="aiDetailTab==='persona'" class="form-section"><div class="section-heading"><h3>人设与关系边界</h3><p>供后端组合 system prompt，避免只留一个大文本框。</p></div><label class="form-field"><span>身份设定</span><textarea v-model="companionForm.persona.identity" rows="3"></textarea></label><div class="form-grid"><label class="form-field"><span>与用户的关系</span><input v-model="companionForm.persona.relationship"/></label><label class="form-field"><span>性格关键词</span><input v-model="companionForm.persona.personality"/></label></div><label class="form-field"><span>语言习惯与表达方式</span><textarea v-model="companionForm.persona.speakingStyle" rows="3"></textarea></label><label class="form-field"><span>关系边界</span><textarea v-model="companionForm.persona.boundaries" rows="3"></textarea></label><label class="form-field"><span>禁忌与禁止模拟</span><textarea v-model="companionForm.persona.forbiddenTopics" rows="3"></textarea></label></div>
              <div v-if="aiDetailTab==='memory'" class="form-section"><div class="section-heading"><h3>长期记忆策略</h3><p>字段只作为后端实现约定，当前浏览器不运行向量检索。</p></div><div class="setting-list"><div class="setting-row"><div><strong>启用长期记忆</strong><span>允许后端保存总结后的用户偏好和关系事件</span></div><button class="switch" :class="{on:companionForm.memorySettings.enabled}" @click="companionForm.memorySettings.enabled=!companionForm.memorySettings.enabled"><i></i></button></div></div><div class="form-grid"><label class="form-field"><span>记忆模式</span><select v-model="companionForm.memorySettings.mode"><option value="hybrid">混合：精选 + 动态</option><option value="curated">仅精选记忆</option><option value="automatic">自动总结</option></select></label><label class="form-field"><span>总结模式</span><select v-model="companionForm.memorySettings.summaryMode"><option value="rolling">滚动总结</option><option value="session">按会话总结</option><option value="manual">仅手动</option></select></label><label class="form-field"><span>时间范围（天）</span><input type="number" v-model.number="companionForm.memorySettings.timeRangeDays"/></label><label class="form-field"><span>每次最多载入</span><input type="number" v-model.number="companionForm.memorySettings.maxItems"/></label><label class="form-field full"><span>向量相似度阈值 {{companionForm.memorySettings.searchThreshold}}</span><input type="range" min="0.3" max="0.95" step="0.01" v-model.number="companionForm.memorySettings.searchThreshold"/></label></div><button class="secondary-action" @click="navigate('memory-lab')"><span v-html="icon('database')"></span>打开记忆数据台</button></div>
              <div v-if="aiDetailTab==='style'" class="form-section"><div class="section-heading"><h3>对话显示与发送节奏</h3><p>从参考图中提取高频、合理的显示项，避免堆砌无意义开关。</p></div><div class="setting-list"><div v-for="item in [{key:'markdown',name:'Markdown 格式',desc:'显示列表、强调和代码块'},{key:'streaming',name:'流式输出',desc:'收到内容后逐步展示'},{key:'typing',name:'显示输入状态',desc:'回复前显示正在输入'},{key:'splitMessages',name:'拆分多条消息',desc:'长回复拆成自然短消息'}]" :key="item.key" class="setting-row"><div><strong>{{item.name}}</strong><span>{{item.desc}}</span></div><button class="switch" :class="{on:companionForm.chatStyle[item.key]}" @click="companionForm.chatStyle[item.key]=!companionForm.chatStyle[item.key]"><i></i></button></div></div><div class="form-grid"><label class="form-field"><span>气泡风格</span><select v-model="companionForm.chatStyle.bubbleStyle"><option value="soft">柔和圆角</option><option value="simple">简洁直角</option><option value="compact">紧凑</option></select></label><label class="form-field"><span>回复延时（毫秒）</span><input type="number" min="0" max="10000" v-model.number="companionForm.chatStyle.replyDelay"/></label></div></div>
              <div v-if="aiDetailTab==='proactive'" class="form-section"><div class="section-heading"><h3>主动陪伴</h3><p>安全替代参考图中的强制锁屏等功能，只保留可控的时间窗和频率。</p></div><div class="setting-list"><div class="setting-row"><div><strong>允许主动发消息</strong><span>后端定时任务按照时间窗触发</span></div><button class="switch" :class="{on:companionForm.proactive.enabled}" @click="companionForm.proactive.enabled=!companionForm.proactive.enabled"><i></i></button></div><div class="setting-row"><div><strong>避开用户忙碌时间</strong><span>后端可结合在线状态和免打扰规则</span></div><button class="switch" :class="{on:companionForm.proactive.avoidBusyTime}" @click="companionForm.proactive.avoidBusyTime=!companionForm.proactive.avoidBusyTime"><i></i></button></div></div><div class="form-grid"><label class="form-field"><span>开始时间</span><input type="time" v-model="companionForm.proactive.start"/></label><label class="form-field"><span>结束时间</span><input type="time" v-model="companionForm.proactive.end"/></label><label class="form-field"><span>主动频率</span><select v-model="companionForm.proactive.frequency"><option value="light">轻量：偶尔想起</option><option value="balanced">平衡：每天 1–3 次</option><option value="daily">固定：每天一次</option><option value="off">关闭</option></select></label><label class="form-field"><span>每日最多次数</span><input type="number" min="0" max="20" v-model.number="companionForm.proactive.dailyLimit"/></label><label class="form-field"><span>最小间隔（分钟）</span><input type="number" v-model.number="companionForm.proactive.minMinutes"/></label><label class="form-field"><span>最大间隔（分钟）</span><input type="number" v-model.number="companionForm.proactive.maxMinutes"/></label></div></div>
              <div v-if="aiDetailTab==='ability'" class="form-section"><div class="section-heading"><h3>角色能力绑定</h3><p>具体模型由 API 配置提供；这里决定该 AI 是否可调用对应后端能力。</p></div><div class="ability-grid"><button v-for="item in capabilityItems.filter(x=>!['autoRead','markdown','streaming','splitMessages','contentFilter','imageConfirm'].includes(x.key))" :key="item.key" class="ability-card" :class="{active:companionForm.capabilities[item.key]}" @click="companionForm.capabilities[item.key]=!companionForm.capabilities[item.key]"><span v-html="icon(item.icon)"></span><strong>{{item.title}}</strong><small>{{item.description}}</small><em>{{companionForm.capabilities[item.key]?'已选择':'未选择'}}</em></button></div></div>
            </div>
          </section>
        </div>

        <!-- 长期记忆与后端数据台 -->
        <div v-if="activeView==='memory-lab'" class="memory-lab page-enter page-width">
          <div class="prototype-banner"><span v-html="icon('info')"></span><div><strong>供后端研发查看的数据结构演示</strong><p>当前不是实际数据库或向量库。页面中的索引、相似度和检索结果均为前端模拟。</p></div><em>FRONTEND MOCK</em></div>
          <div class="metric-grid memory-metrics"><article><span v-html="icon('database')"></span><div><strong>{{memoryCount}}</strong><small>长期记忆记录</small></div></article><article><span v-html="icon('vector')"></span><div><strong>{{memoryCount-1}}</strong><small>模拟已索引</small></div></article><article><span v-html="icon('brain')"></span><div><strong>1536</strong><small>向量维度占位</small></div></article><article><span v-html="icon('clock')"></span><div><strong>{{settings.advanced.contextTurns}}</strong><small>上下文轮数</small></div></article></div>
          <div class="tab-strip"><button v-for="tab in [{id:'records',name:'记忆记录'},{id:'vector',name:'向量检索调试'},{id:'contract',name:'接口契约'}]" :key="tab.id" :class="{active:memoryLabTab===tab.id}" @click="memoryLabTab=tab.id">{{tab.name}}</button></div>
          <section v-if="memoryLabTab==='records'" class="memory-workspace"><div class="memory-list card-surface"><div class="panel-title"><div><h2>长期记忆记录</h2><p>偏好、事件、关系、摘要使用统一记录模型。</p></div><button class="secondary-action" @click="openMemoryDialog()">添加</button></div><article v-for="memory in allMemories" :key="memory.id" class="memory-row"><span class="memory-kind">{{memoryTypeLabel(memory.type)}}</span><div><strong>{{memory.title}}</strong><p>{{memory.content}}</p><small>{{memory.companion.name}} · {{memory.date}} · {{memory.source}}</small></div><div class="memory-state"><em :class="memory.embeddingStatus">{{memory.embeddingStatus==='indexed'?'已索引':'待索引'}}</em><button @click="openMemoryDialog(memory)"><span v-html="icon('edit')"></span></button><button @click="removeMemory(memory)"><span v-html="icon('trash')"></span></button></div></article><div v-if="!allMemories.length" class="mini-empty">暂无记忆记录</div></div><aside class="memory-schema card-surface"><span class="soft-label">RECORD SCHEMA</span><h3>MemoryRecord</h3><dl><div><dt>id</dt><dd>string</dd></div><div><dt>companionId</dt><dd>string</dd></div><div><dt>type</dt><dd>preference / event / relationship</dd></div><div><dt>content</dt><dd>text</dd></div><div><dt>importance</dt><dd>0–1</dd></div><div><dt>sourceMessageId</dt><dd>nullable string</dd></div><div><dt>embeddingStatus</dt><dd>pending / indexed</dd></div></dl></aside></section>
          <section v-if="memoryLabTab==='vector'" class="vector-layout"><div class="vector-console card-surface"><div class="section-heading"><h3>向量检索调试</h3><p>输入一段当前消息，查看模拟召回结果。</p></div><label class="form-field"><span>检索文本</span><textarea v-model="memorySearchQuery" rows="4"></textarea></label><div class="form-grid"><label class="form-field"><span>集合名</span><input value="qinban_companion_memory" readonly/></label><label class="form-field"><span>Embedding 模型</span><input value="由后端选择" readonly/></label><label class="form-field"><span>Top K</span><input value="8" readonly/></label><label class="form-field"><span>相似度阈值</span><input :value="activeCompanion?.memorySettings.searchThreshold||0.65" readonly/></label></div><button class="primary-action" @click="runMemorySearch"><span v-html="icon('search')"></span>运行前端模拟检索</button></div><div class="retrieval-results card-surface"><div class="panel-title"><div><h3>召回结果</h3><p>按模拟相似度排序</p></div><span class="status-chip pending">非真实向量</span></div><article v-for="item in memorySearchResults" :key="item.id"><em>{{item.score}}</em><div><strong>{{item.title}}</strong><p>{{item.content}}</p><small>{{item.companion.name}} · {{memoryTypeLabel(item.type)}}</small></div></article><div v-if="!memorySearchResults.length" class="mini-empty">点击左侧按钮后显示检索结果</div></div></section>
          <section v-if="memoryLabTab==='contract'" class="contract-layout"><div class="card-surface contract-card"><div class="section-heading"><h3>建议接口契约</h3><p>便于前后端围绕同一份字段继续开发。</p></div><pre>{{backendContractPreview}}</pre></div><div class="card-surface pipeline-card"><h3>后端处理链路</h3><ol><li><b>1</b><div><strong>消息入库</strong><p>原始消息与会话 ID 持久化</p></div></li><li><b>2</b><div><strong>记忆抽取与确认</strong><p>偏好、事件和关系变更结构化</p></div></li><li><b>3</b><div><strong>Embedding 与索引</strong><p>按 companionId 隔离向量集合</p></div></li><li><b>4</b><div><strong>检索与上下文组装</strong><p>阈值、时间范围、Token 预算共同约束</p></div></li><li><b>5</b><div><strong>总结与审计</strong><p>保存注入来源，支持删除和重建</p></div></li></ol></div></section>
        </div>
        <!-- 我的 -->
        <div v-if="activeView==='mine'" class="mine-page page-enter page-width narrow-page">
          <section class="profile-hero card-surface"><div class="user-avatar xl" :style="userAvatarStyle()"><span v-if="!settings.userAvatar">{{userInitial}}</span></div><div><h2>{{settings.nickname}}</h2><p>{{settings.signature}}</p></div><button class="secondary-action" @click="editProfile"><span v-html="icon('edit')"></span>编辑资料</button></section>
          <section class="mine-section mine-simple-menu card-surface"><button class="menu-row" @click="openSettings('api')"><span class="settings-icon mint" v-html="icon('settings')"></span><div><strong>设置</strong><span>账号、外观与使用设置</span></div><span class="chevron">›</span></button><button class="menu-row" @click="openUtility('my-moments')"><span class="settings-icon coral" v-html="icon('moments')"></span><div><strong>朋友圈</strong><span>{{myMoments.length}} 条自己发布的动态</span></div><span class="chevron">›</span></button></section>
        </div>

        <!-- 设置中心 -->
        <div v-if="activeView==='settings'" class="settings-page page-enter page-width">
          <div class="prototype-banner"><span v-html="icon('shield')"></span><div><strong>API Key 仅用于当前浏览器联调</strong><p>正式产品必须由后端代理请求并安全保存密钥。模型识别可能受 CORS、协议和权限影响。</p></div><em>FRONTEND ONLY</em></div>
          <div class="tab-strip settings-tabs"><button v-for="tab in [{id:'api',name:'API 与模型'},{id:'capabilities',name:'能力设置'},{id:'appearance',name:'外观与消息'},{id:'advanced',name:'高级与数据'}]" :key="tab.id" :class="{active:settingsTab===tab.id}" @click="settingsTab=tab.id">{{tab.name}}</button></div>
          <section v-if="settingsTab==='api'" class="api-settings-layout">
            <aside class="api-profile-list card-surface"><div class="panel-title"><div><h3>API 配置</h3><p>可为不同 AI 绑定不同配置</p></div><button class="icon-action" @click="addApiProfile"><span v-html="icon('plus')"></span></button></div><button v-for="p in apiProfiles" :key="p.id" class="api-profile-button" :class="{active:selectedApiId===p.id}" @click="selectedApiId=p.id"><span class="api-status-dot" :class="p.status"></span><div><strong>{{p.name}}</strong><small>{{p.provider}} · {{p.enabled?'已启用':'未启用'}}</small></div><span class="chevron">›</span></button><div class="api-side-note"><span v-html="icon('info')"></span><p>“内置服务商”只预填分类和协议入口，不包含任何平台密钥，也不保证模型可用。</p></div></aside>
            <div v-if="activeApiProfile" class="api-profile-editor card-surface"><div class="panel-title"><div><span class="soft-label">SERVICE PROFILE</span><h2>{{activeApiProfile.name}}</h2><p>{{activeApiProfile.lastTest}}</p></div><div class="inline-actions"><button class="switch" :class="{on:activeApiProfile.enabled}" @click="activeApiProfile.enabled=!activeApiProfile.enabled;persist()"><i></i></button><button class="icon-action danger" @click="removeApiProfile(activeApiProfile)"><span v-html="icon('trash')"></span></button></div></div>
              <div class="provider-section"><span class="field-label">国内 / 国外 / 本地服务商入口</span><div class="provider-chips"><button v-for="provider in providerOptions" :key="provider.name" :class="{active:activeApiProfile.provider===provider.name}" @click="selectProvider(activeApiProfile,provider)"><strong>{{provider.name}}</strong><small>{{provider.region}}</small></button></div></div>
              <div class="form-grid"><label class="form-field"><span>配置名称</span><input v-model="activeApiProfile.name"/></label><label class="form-field"><span>协议类型</span><select v-model="activeApiProfile.protocol"><option value="chat-completions">OpenAI Chat Completions</option><option value="openai-compatible">OpenAI 兼容</option><option value="responses">Responses 风格（待后端）</option><option value="custom">自定义适配器（待后端）</option></select></label><label class="form-field full"><span>Base URL</span><input v-model="activeApiProfile.baseUrl" placeholder="https://your-provider.example/v1"/></label><label class="form-field full"><span>API Key</span><input type="password" v-model="activeApiProfile.apiKey" placeholder="仅保存在当前浏览器；正式产品禁止前端保存"/></label></div>
              <div class="model-grid"><label class="form-field"><span>主对话模型</span><input v-model="activeApiProfile.chatModel" placeholder="model-id"/></label><label class="form-field"><span>辅助视觉模型</span><input v-model="activeApiProfile.visionModel" placeholder="vision-model-id"/></label><label class="form-field"><span>辅助听觉 / ASR</span><input v-model="activeApiProfile.hearingModel" placeholder="speech-to-text-model"/></label><label class="form-field"><span>TTS 模型</span><input v-model="activeApiProfile.ttsModel" placeholder="text-to-speech-model"/></label><label class="form-field"><span>声音复刻模型</span><input v-model="activeApiProfile.voiceCloneModel" placeholder="voice-clone-model"/></label><label class="form-field"><span>视频理解模型</span><input v-model="activeApiProfile.videoModel" placeholder="video-model"/></label><label class="form-field"><span>文生图模型</span><input v-model="activeApiProfile.imageModel" placeholder="image-generation-model"/></label><label class="form-field"><span>回复温度 {{activeApiProfile.temperature}}</span><input type="range" min="0" max="2" step="0.1" v-model.number="activeApiProfile.temperature"/></label></div>
              <div class="model-detect"><div><h3>点击识别模型</h3><p>配置允许跨域的 API 后读取 /models；否则展示明确标注的示例目录。</p></div><button class="primary-action" :disabled="modelDetecting" @click="detectModels(activeApiProfile)"><span v-html="icon('refresh')"></span>{{modelDetecting?'识别中…':'识别模型 / 获取列表'}}</button></div>
              <div v-if="activeApiProfile.detectedModels.length" class="detected-models"><button v-for="model in activeApiProfile.detectedModels" :key="model.id" @click="applyDetectedModel(activeApiProfile,model)"><strong>{{model.id}}</strong><span><em v-for="c in model.capabilities" :key="c">{{c}}</em></span><small>设为主模型</small></button></div>
            </div>
          </section>
          <section v-if="settingsTab==='capabilities'" class="capability-settings"><div class="section-intro card-surface"><div><span class="soft-label">GLOBAL CAPABILITY SWITCHES</span><h2>能力总开关</h2><p>开关表示产品希望启用该能力，不表示后端模型已经可用。每个 AI 还需要在角色页单独授权。</p></div><span class="status-chip pending">{{enabledCapabilityCount}} 项已选择</span></div><div class="capability-grid"><article v-for="item in capabilityItems" :key="item.key" class="capability-setting card-surface"><span class="settings-icon" :class="settings.globalCapabilities[item.key]?'purple':'neutral'" v-html="icon(item.icon)"></span><div><strong>{{item.title}}</strong><p>{{item.description}}</p><small>前端配置占位 · 等待后端能力接入</small></div><button class="switch" :class="{on:settings.globalCapabilities[item.key]}" @click="toggleCapability(item.key)"><i></i></button></article></div></section>
          <section v-if="settingsTab==='appearance'" class="appearance-layout"><div class="appearance-preview card-surface"><span class="soft-label">CHAT PREVIEW</span><h3>清晰、克制的聊天显示</h3><div class="preview-chat"><div class="preview-system">今天 18:20</div><div class="preview-line"><div class="avatar small-avatar">沐</div><div class="preview-bubble">文字保持足够清晰，长聊天只在页内滚动。</div></div><div class="preview-line mine"><div class="preview-bubble">界面不会再无限向下撑开。</div></div></div></div><div class="appearance-controls card-surface"><div class="section-heading"><h3>主题与聊天排版</h3><p>只保留实际影响阅读的少量设置。</p></div><div class="theme-options"><button :class="{active:settings.theme==='light'}" @click="settings.theme='light'"><span v-html="icon('sun')"></span><strong>浅色</strong></button><button :class="{active:settings.theme==='dark'}" @click="settings.theme='dark'"><span v-html="icon('moon')"></span><strong>深色</strong></button></div><label class="form-field"><span>字体大小</span><select v-model="settings.fontSize"><option value="compact">紧凑</option><option value="comfortable">舒适</option><option value="large">较大</option></select></label><label class="form-field"><span>气泡圆角 {{settings.bubbleRadius}}px</span><input type="range" min="6" max="28" v-model.number="settings.bubbleRadius"/></label><label class="form-field"><span>消息间距 {{settings.messageGap}}px</span><input type="range" min="8" max="24" v-model.number="settings.messageGap"/></label><div class="setting-list"><div class="setting-row"><div><strong>通知提示</strong><span>仅前端状态，不请求系统权限</span></div><button class="switch" :class="{on:settings.notifications}" @click="settings.notifications=!settings.notifications"><i></i></button></div><div class="setting-row"><div><strong>夜间免打扰</strong><span>{{settings.quietStart}} 至 {{settings.quietEnd}}</span></div><button class="switch" :class="{on:settings.quietHours}" @click="settings.quietHours=!settings.quietHours"><i></i></button></div></div></div></section>
          <section v-if="settingsTab==='advanced'" class="advanced-layout"><div class="advanced-card card-surface"><div class="section-heading"><h3>上下文与总结</h3><p>对应参考图中的高频设置，统一收拢为后端参数。</p></div><label class="form-field"><span>上下文加载轮数 {{settings.advanced.contextTurns}}</span><input type="range" min="4" max="80" step="2" v-model.number="settings.advanced.contextTurns"/></label><label class="form-field"><span>总结模式</span><select v-model="settings.advanced.summaryMode"><option value="hybrid">混合：滚动总结 + 最近消息</option><option value="rolling">仅滚动总结</option><option value="full">完整加载（高消耗）</option></select></label><label class="form-field"><span>记忆模糊搜索阈值 {{settings.advanced.memoryThreshold}}</span><input type="range" min="0.3" max="0.95" step="0.01" v-model.number="settings.advanced.memoryThreshold"/></label><label class="form-field"><span>多条消息延时 {{settings.advanced.sendDelay}}ms</span><input type="range" min="0" max="3000" step="100" v-model.number="settings.advanced.sendDelay"/></label><div class="setting-list"><div class="setting-row"><div><strong>Prompt 模块注入</strong><span>按能力组合系统提示模块</span></div><button class="switch" :class="{on:settings.advanced.promptModules}" @click="settings.advanced.promptModules=!settings.advanced.promptModules"><i></i></button></div><div class="setting-row"><div><strong>显示对方输入状态</strong><span>等待模型回复时显示动画</span></div><button class="switch" :class="{on:settings.advanced.typingIndicator}" @click="settings.advanced.typingIndicator=!settings.advanced.typingIndicator"><i></i></button></div><div class="setting-row"><div><strong>前端调试日志</strong><span>仅记录非敏感状态摘要</span></div><button class="switch" :class="{on:settings.advanced.debugLog}" @click="settings.advanced.debugLog=!settings.advanced.debugLog"><i></i></button></div></div></div><div class="advanced-card card-surface"><div class="section-heading"><h3>自定义请求参数</h3><p>提供给后端适配器参考，不建议普通用户修改。</p></div><label class="form-field"><span>JSON</span><textarea class="code-editor" v-model="settings.advanced.customRequestJson" rows="10"></textarea></label><div class="inline-actions"><button class="secondary-action" @click="validateRequestJson">校验 JSON</button><button class="secondary-action" @click="exportLogs"><span v-html="icon('download')"></span>导出诊断日志</button></div><div class="privacy-note"><span v-html="icon('shield')"></span><p>日志不会导出 API Key。正式 SDK、服务商适配和隐私审计由后端实现。</p></div></div></section>
        </div>

        <!-- API 消耗诊断 -->
        <div v-if="activeView==='usage'" class="usage-page page-enter page-width">
          <section class="usage-hero card-surface"><div><span class="soft-label">FRONTEND ESTIMATE</span><h2>当前预计消耗 <em :class="usageLevel.tone">{{usageLevel.label}}</em></h2><p>基于上下文轮数、记忆数量、角色设定和能力开关进行演示估算，不代表任何供应商真实账单。</p></div><div class="score-ring" :style="{'--score':usageLevel.score}"><strong>{{usageLevel.score}}</strong><span>/100</span></div></section>
          <div class="usage-grid"><article class="card-surface"><span>预计输入 + 输出 Token</span><strong>{{estimatedTokens.toLocaleString()}}</strong><small>一次典型长会话的演示估算</small></article><article class="card-surface"><span>示例费用</span><strong>¥{{estimatedCost}}</strong><small>仅使用占位单价，不能用于结算</small></article><article class="card-surface"><span>上下文轮数</span><strong>{{settings.advanced.contextTurns}}</strong><small>{{settings.advanced.summaryMode==='full'?'完整加载会显著增加消耗':'已启用受控加载'}}</small></article><article class="card-surface"><span>人设与记忆</span><strong>{{personaChars+memoryCount*120}} 字</strong><small>{{memoryCount}} 条长期记忆候选</small></article></div>
          <div class="diagnostic-layout"><section class="card-surface diagnostic-list"><div class="panel-title"><div><h3>消耗构成诊断</h3><p>方便产品与后端讨论默认参数。</p></div><span class="status-chip pending">前端估算</span></div><div class="diagnostic-row"><span>发送时加载范围</span><strong>{{settings.advanced.contextTurns}} 轮</strong><em :class="settings.advanced.contextTurns>40?'high':'ok'">{{settings.advanced.contextTurns>40?'偏高':'合理'}}</em></div><div class="diagnostic-row"><span>记忆库设置</span><strong>{{memoryCount}} 条 / 阈值 {{settings.advanced.memoryThreshold}}</strong><em class="ok">受控</em></div><div class="diagnostic-row"><span>深度思考</span><strong>未配置真实字段</strong><em class="neutral">待后端</em></div><div class="diagnostic-row"><span>主模型</span><strong>{{activeApiProfile?.chatModel||'未设置'}}</strong><em class="neutral">{{activeApiProfile?.enabled?'已选择':'未启用'}}</em></div><div class="diagnostic-row"><span>视觉 / TTS / 生图</span><strong>{{['vision','tts','imageGeneration'].filter(k=>settings.globalCapabilities[k]).length}} 项开启</strong><em class="neutral">按调用计费</em></div><div class="diagnostic-row"><span>AI 群聊</span><strong>最多 {{Math.max(...groups.map(g=>g.strategy.maxSpeakers),0)}} 位 / 轮</strong><em class="neutral">模拟</em></div></section><section class="card-surface trend-card"><div class="section-heading"><h3>7 日趋势占位</h3><p>后端接入真实 usage 后替换。</p></div><div class="fake-chart"><i v-for="h in [28,52,36,72,44,62,48]" :style="{height:h+'%'}"></i></div><div class="chart-labels"><span>周一</span><span>周二</span><span>周三</span><span>周四</span><span>周五</span><span>周六</span><span>今天</span></div></section></div>
          <section class="optimization-card card-surface"><span class="settings-icon mint" v-html="icon('sparkle')"></span><div><h3>优化建议</h3><ul><li>默认保留 12–24 轮最近对话，旧内容使用滚动总结。</li><li>向量检索按相似度、时间与 Token 预算共同截断。</li><li>视觉、语音、视频和生图只在用户明确触发时调用。</li><li>群聊限制每轮发言 AI 数量，避免重复回答和并发浪费。</li></ul></div><button class="secondary-action" @click="openSettings('advanced')">调整参数</button></section>
        </div>
      </section>

      <nav class="bottom-nav" v-if="activeView!=='chat'&&!isSecondaryView"><button v-for="item in mobileNavItems" :key="item.id" :class="{active:activeView===item.id}" @click="navigate(item.id)"><span v-html="icon(item.icon)"></span><em>{{item.label==='AI 通讯录'?'通讯录':item.label==='AI 朋友圈'?'朋友圈':item.label==='AI 与群聊'?'AI':item.label}}</em></button></nav>
    </main>
  </div>

  <!-- 群聊创建与编辑 -->
  <div v-if="showGroupDialog" class="modal-backdrop" @click.self="closeModal"><section class="modal-card wide-modal"><div class="modal-head"><div><span class="soft-label">AI GROUP CHAT</span><h2>{{groupForm.id?'编辑 AI 群聊':'创建 AI 群聊'}}</h2></div><button class="round-action" @click="closeModal"><span v-html="icon('close')"></span></button></div><div class="modal-scroll"><div class="group-form-head"><div class="avatar hero-avatar" :style="avatarStyle(groupForm)"><span v-if="!groupForm.avatarImage">{{groupForm.initial||groupForm.name?.slice(0,1)||'群'}}</span></div><label class="avatar-upload"><input type="file" accept="image/*" @change="handleImageUpload($event,'group')"/><span v-html="icon('image')"></span>群头像</label></div><div class="form-grid"><label class="form-field"><span>群名称</span><input v-model="groupForm.name" placeholder="例如：晚风茶话会"/></label><label class="form-field"><span>文字头像</span><input v-model="groupForm.initial" maxlength="2"/></label><label class="form-field full"><span>群公告 / 调度说明</span><textarea v-model="groupForm.announcement" rows="2"></textarea></label></div><div class="subsection-title"><strong>选择 AI 成员</strong><span>至少 2 位</span></div><div class="member-picker"><button v-for="item in companions" :key="item.id" :class="{active:groupForm.memberIds?.includes(item.id)}" @click="toggleGroupMember(item.id)"><div class="avatar" :style="avatarStyle(item)"><span v-if="!item.avatarImage">{{item.initial}}</span></div><strong>{{item.name}}</strong><small>{{item.category}}</small><i v-html="icon('check')"></i></button></div><div class="subsection-title"><strong>多 AI 主动聊天</strong><span>仅保存前端参数</span></div><div class="setting-list"><div class="setting-row"><div><strong>启用主动群聊</strong><span>群成员可在时间窗内自主开启话题</span></div><button class="switch" :class="{on:groupForm.strategy.enabled}" @click="groupForm.strategy.enabled=!groupForm.strategy.enabled"><i></i></button></div></div><div class="form-grid"><label class="form-field"><span>发言模式</span><select v-model="groupForm.strategy.mode"><option value="random">随机发言</option><option value="turn">按顺序发言</option></select></label><label class="form-field"><span>成员排序</span><select v-model="groupForm.strategy.order"><option value="balanced">平衡参与</option><option value="member-order">按成员顺序</option><option value="random">完全随机</option></select></label><label class="form-field"><span>冷却时间（秒）</span><input type="number" v-model.number="groupForm.strategy.cooldownSeconds"/></label><label class="form-field"><span>每轮最多发言数</span><input type="number" min="1" max="8" v-model.number="groupForm.strategy.maxSpeakers"/></label></div></div><div class="modal-foot"><button v-if="groupForm.id" class="danger-action" @click="removeGroup(groupForm);closeModal()">删除群聊</button><span></span><button class="secondary-action" @click="closeModal">取消</button><button class="primary-action" @click="saveGroup"><span v-html="icon('check')"></span>保存群聊</button></div></section></div>
  <!-- 个人资料 -->
  <div v-if="showProfileDialog" class="modal-backdrop" @click.self="closeModal"><section class="modal-card"><div class="modal-head"><div><span class="soft-label">USER PERSONA</span><h2>个人资料与用户画像</h2></div><button class="round-action" @click="closeModal"><span v-html="icon('close')"></span></button></div><div class="modal-scroll"><div class="group-form-head"><div class="user-avatar xl" :style="{backgroundImage:profileForm.userAvatar?`url('${profileForm.userAvatar}')`:'none'}"><span v-if="!profileForm.userAvatar">{{profileForm.nickname?.slice(0,1)||'你'}}</span></div><label class="avatar-upload"><input type="file" accept="image/*" @change="handleImageUpload($event,'user')"/><span v-html="icon('image')"></span>更换头像</label></div><div class="form-grid"><label class="form-field"><span>昵称</span><input v-model="profileForm.nickname" maxlength="20"/></label><label class="form-field"><span>一句话签名</span><input v-model="profileForm.signature" maxlength="60"/></label><label class="form-field full"><span>个人人设 / 希望被如何陪伴</span><textarea v-model="profileForm.userPersona" rows="5"></textarea></label></div><div class="privacy-note"><span v-html="icon('shield')"></span><p>当前画像只保存在本机。后端接入后应提供查看、导出、删除和关闭记忆的能力。</p></div></div><div class="modal-foot"><button class="secondary-action" @click="closeModal">取消</button><button class="primary-action" @click="saveProfile">保存资料</button></div></section></div>

  <!-- 记忆记录 -->
  <div v-if="showMemoryDialog" class="modal-backdrop" @click.self="closeModal"><section class="modal-card"><div class="modal-head"><div><span class="soft-label">MEMORY RECORD</span><h2>{{memoryForm.id?'编辑长期记忆':'添加长期记忆'}}</h2></div><button class="round-action" @click="closeModal"><span v-html="icon('close')"></span></button></div><div class="modal-scroll"><div class="form-grid"><label class="form-field"><span>归属 AI</span><select v-model="memoryForm.companionId"><option v-for="item in companions" :key="item.id" :value="item.id">{{item.name}}</option></select></label><label class="form-field"><span>类型</span><select v-model="memoryForm.type"><option value="preference">用户偏好</option><option value="event">关系事件</option><option value="relationship">关系记忆</option><option value="summary">对话摘要</option></select></label><label class="form-field full"><span>标题</span><input v-model="memoryForm.title"/></label><label class="form-field full"><span>内容</span><textarea v-model="memoryForm.content" rows="5"></textarea></label><label class="form-field"><span>重要度 {{memoryForm.importance}}</span><input type="range" min="0" max="1" step="0.01" v-model.number="memoryForm.importance"/></label><label class="form-field"><span>索引状态</span><select v-model="memoryForm.embeddingStatus"><option value="pending">待索引</option><option value="indexed">已索引（演示）</option></select></label></div></div><div class="modal-foot"><button class="secondary-action" @click="closeModal">取消</button><button class="primary-action" @click="saveMemory">保存记忆</button></div></section></div>

  <!-- 发布朋友圈 -->
  <div v-if="showMomentDialog" class="modal-backdrop" @click.self="closeModal"><section class="modal-card"><div class="modal-head"><div><span class="soft-label">NEW MOMENT</span><h2>发布朋友圈动态</h2></div><button class="round-action" @click="closeModal"><span v-html="icon('close')"></span></button></div><div class="modal-scroll"><label class="form-field"><span>内容</span><textarea v-model="momentForm.content" rows="7" maxlength="500" placeholder="分享一段今天的想法…"></textarea></label><div class="form-grid"><label class="form-field"><span>可见范围</span><select v-model="momentForm.visibility"><option>所有好友</option><option>仅你可见</option><option>部分 AI 可见</option></select></label><label class="form-field"><span>图片占位</span><select v-model="momentForm.imageTone"><option value="">无图片</option><option value="lavender">薰衣草色</option><option value="mint">薄荷色</option><option value="coral">暖珊瑚色</option></select></label></div><div class="privacy-note"><span v-html="icon('info')"></span><p>当前发布只写入本机 localStorage，不会上传到网络。</p></div></div><div class="modal-foot"><button class="secondary-action" @click="closeModal">取消</button><button class="primary-action" @click="publishMoment">发布动态</button></div></section></div>

  <!-- 我的页面信息弹窗 -->
  <div v-if="utilityPanel" class="modal-backdrop" @click.self="closeModal"><section class="modal-card utility-modal"><div class="modal-head"><div><span class="soft-label">QINBAN INFO</span><h2>{{utilityPanel==='my-moments'?'我的朋友圈':utilityPanel==='favorites'?'我的收藏':utilityPanel==='team'?'开发团队':utilityPanel==='agreement'?'用户协议与隐私政策':'更新说明'}}</h2></div><button class="round-action" @click="closeModal"><span v-html="icon('close')"></span></button></div><div class="modal-scroll utility-content">
    <div v-if="utilityPanel==='my-moments'"><article v-for="item in myMoments" :key="item.id" class="favorite-row"><div class="user-avatar" :style="userAvatarStyle()"><span v-if="!settings.userAvatar">{{userInitial}}</span></div><div><strong>{{settings.nickname}}</strong><p>{{item.content}}</p><small>{{formatRelativeTime(item.createdAt)}} · {{item.visibility}}</small></div></article><div v-if="!myMoments.length" class="mini-empty">你还没有发布朋友圈</div></div>
    <div v-if="utilityPanel==='favorites'"><article v-for="item in savedMoments" :key="item.id" class="favorite-row"><div class="avatar" :style="avatarStyle(momentAuthor(item))"><span>{{momentAuthor(item).initial}}</span></div><div><strong>{{momentAuthor(item).name}}</strong><p>{{item.content}}</p></div><button @click="toggleMomentSave(item)"><span v-html="icon('bookmark')"></span></button></article><div v-if="!savedMoments.length" class="mini-empty">还没有收藏内容</div></div>
    <div v-if="utilityPanel==='team'" class="document-copy"><p>亲伴当前阶段由前端原型与后端研发协作完成。此页面只保留团队职能和仓库交付说明，不引用任何参考产品中的 QQ、客服、赞助者或其他外部联系方式。</p><h3>前端当前职责</h3><ul><li>页面信息架构与响应式布局</li><li>可点击交互和本地模拟数据</li><li>API、记忆、多 AI 群聊的数据契约展示</li></ul><h3>后端后续职责</h3><ul><li>账号、会话、长期记忆、向量检索</li><li>API 密钥代理、模型路由与用量统计</li><li>主动消息、多 AI 调度、语音视觉与安全审计</li></ul></div>
    <div v-if="utilityPanel==='agreement'" class="document-copy"><h3>原型阶段说明</h3><p>本原型数据默认保存在当前浏览器。API Key 如被填写也只用于本机联调，导出数据时会移除。正式版本必须迁移到安全的后端密钥管理。</p><h3>隐私与控制权</h3><ul><li>用户应能查看、导出、修改和删除个人数据与 AI 记忆。</li><li>声音复刻必须获得明确授权，支持撤销和审计。</li><li>不实现强制锁屏、读取设备使用情况或控制设备等高风险功能。</li><li>AI 不冒充现实人员，不诱导依赖，不替代医疗或紧急支持。</li></ul></div>
    <div v-if="utilityPanel==='updates'" class="document-copy"><h3>v0.4.0-frontend · 2026-09-03</h3><ul><li>补齐会话、通讯录、AI 群聊和多角色消息原型。</li><li>新增 AI 朋友圈、点赞、评论、收藏与主动发布模拟。</li><li>新增详细人设、记忆、风格、主动频率与能力设置。</li><li>新增后端记忆数据台、向量检索调试和接口契约。</li><li>新增多 API 配置、模型识别、能力设置和用量诊断。</li><li>重新约束应用高度与页面内部滚动，优化文字清晰度。</li></ul><h3>当前状态</h3><p>仅供本地审核，尚未作为本轮更新提交或推送仓库。</p></div>
  </div><div class="modal-foot"><button class="primary-action full" @click="closeModal">知道了</button></div></section></div>

  <div v-if="showAbout" class="modal-backdrop" @click.self="showAbout=false"><section class="modal-card about-modal"><div class="about-mark"><div class="brand-mark"><img src="/assets/qinban-icon.svg" alt="" /></div></div><span class="soft-label">亲伴 · FRONTEND PROTOTYPE</span><h2>页面先完整，<br/><em>能力后接入。</em></h2><p>亲伴希望用数字方式珍藏重要亲人的记忆，让熟悉的故事、语气和陪伴在安全边界内被好好记住。</p><div class="about-points"><div><span v-html="icon('shield')"></span><strong>安全边界</strong><small>尊重逝者与家属的授权、隐私和退出权</small></div><div><span v-html="icon('database')"></span><strong>记忆可见</strong><small>支持查看、导出、修改和删除数字记忆</small></div><div><span v-html="icon('palette')"></span><strong>温和陪伴</strong><small>用清晰克制的方式承接思念，不制造依赖</small></div></div><button class="primary-action full" @click="showAbout=false">开始审核</button></section></div>

  <input ref="importFile" class="sr-only" type="file" accept="application/json" @change="importData"/>
  <transition name="toast"><div v-if="toastMessage" class="toast-message"><span v-html="icon('check')"></span>{{toastMessage}}</div></transition>
</div>
</template>
<script>
import { appOptions } from './app.js'
export default appOptions
</script>
<style src="./style.css"></style>
